// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using menu_serve_api.Models;

namespace menuserveapi.Migrations
{
    [DbContext(typeof(MenuServeDBContext))]
    [Migration("20180531150949_removed_enum_type_added_menu_order")]
    partial class removed_enum_type_added_menu_order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("menu_serve_api.Models.MenuCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Menu_Categories");

                    b.HasData(
                        new { ID = 1, DisplayOrder = 1, Name = "Starters" },
                        new { ID = 2, DisplayOrder = 2, Name = "Mains" },
                        new { ID = 3, DisplayOrder = 5, Name = "Drinks" },
                        new { ID = 4, DisplayOrder = 4, Name = "Sides" },
                        new { ID = 5, DisplayOrder = 3, Name = "Deserts" }
                    );
                });

            modelBuilder.Entity("menu_serve_api.Models.MenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnName("Details")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("MenuCategoryID");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnName("Short_Description")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("MenuCategoryID");

                    b.ToTable("Menu_Items");

                    b.HasData(
                        new { ID = 1, Details = "A long description of what this menu item is", MenuCategoryID = 1, Price = 9.99m, ShortDescription = "Short description of item" },
                        new { ID = 2, Details = "Another long description of what this menu item is", MenuCategoryID = 2, Price = 8.88m, ShortDescription = "Another description" }
                    );
                });

            modelBuilder.Entity("menu_serve_api.Models.MenuItem", b =>
                {
                    b.HasOne("menu_serve_api.Models.MenuCategory", "MenuCategory")
                        .WithMany()
                        .HasForeignKey("MenuCategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
