// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using menu_serve_api.Models;

namespace menuserveapi.Migrations
{
    [DbContext(typeof(MenuServeDBContext))]
    [Migration("20180527010302_seed_data")]
    partial class seed_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("menu_serve_api.Models.MenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnName("Details");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnName("Short_Description");

                    b.HasKey("ID");

                    b.ToTable("Menu_Items");

                    b.HasData(
                        new { ID = 1, Details = "A long description of what this menu item is", Price = 9.99m, ShortDescription = "Short description of item" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
