// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using menu_serve_api.Models;

namespace menuserveapi.Migrations
{
    [DbContext(typeof(MenuServeDBContext))]
    partial class MenuServeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("menu_serve_api.Models.MenuCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Menu_Categories");

                    b.HasData(
                        new { ID = 1, Name = "Starters" },
                        new { ID = 2, Name = "Mains" },
                        new { ID = 3, Name = "Deserts" },
                        new { ID = 4, Name = "Sides" },
                        new { ID = 5, Name = "Drinks" }
                    );
                });

            modelBuilder.Entity("menu_serve_api.Models.MenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnName("Details")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("MenuCategoryID");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnName("Short_Description")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("MenuCategoryID");

                    b.ToTable("Menu_Items");

                    b.HasData(
                        new { ID = 1, Details = "A long description of what this menu item is", MenuCategoryID = 1, Price = 9.99m, ShortDescription = "Short description of item" },
                        new { ID = 2, Details = "Another long description of what this menu item is", MenuCategoryID = 2, Price = 8.88m, ShortDescription = "Another description" }
                    );
                });

            modelBuilder.Entity("menu_serve_api.Models.MenuItem", b =>
                {
                    b.HasOne("menu_serve_api.Models.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
